/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.ModuloConexao;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import static telas.NovaGuia.btnSalvar;
import static telas.NovaGuia.txtBaseCalculo;
import static telas.NovaGuia.txtData;
import static telas.NovaGuia.txtId;
import static telas.NovaGuia.txtNumero;
import static telas.NovaGuia.cbSecretaria;
import static telas.NovaGuia.txtData;
import static telas.NovaGuia.txtObservacao;
import static telas.NovaGuia.txtTotalGeral;
import static telas.NovaGuia.txtTotalPatronal;
import static telas.NovaGuia.txtValPatronal;
import static telas.NovaGuia.txtValServidor;
import static telas.NovaGuia.txtValSuplementar;
import static telas.Principal.desktop;

/**
 *
 * @author carlos
 */
public class BancoDeDados extends javax.swing.JInternalFrame {

    /**
     * Creates new form BancoDeDados
     */
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public BancoDeDados() {
        initComponents();
        conn = ModuloConexao.conector();
        
    }
    
    public void pesquisar(){  
        String sql = "SELECT *FROM tbGuias WHERE MONTH(GUI_DATA_CADASTRO) = ? "
                + "AND YEAR(GUI_DATA_CADASTRO) = ?" ;
       
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtPesquisar.getText().substring(1, 3));
            pst.setString(2, txtPesquisar.getText().substring(3, 7));
            rs = pst.executeQuery();
            
            tbBanco.setModel(DbUtils.resultSetToTableModel(rs));
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
              
        int setar = tbBanco.getSelectedRow();
    }
    
    private void selectAll(){
        String sql  = "SELECT *FROM tbGuias";
        
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tbBanco.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbBanco = new javax.swing.JTable();
        btnBdExluir = new javax.swing.JButton();
        btnBdEditar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Tabela de dados");
        setPreferredSize(new java.awt.Dimension(680, 480));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tbBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Título 3", "Título 4", "Título 5", "Título 6", "Título 7"
            }
        ));
        tbBanco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbBancoFocusGained(evt);
            }
        });
        tbBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBancoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbBanco);

        btnBdExluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-excluir-arquivo-24.png"))); // NOI18N
        btnBdExluir.setText("Excluir");
        btnBdExluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBdExluirActionPerformed(evt);
            }
        });

        btnBdEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-editar-arquivo-24.png"))); // NOI18N
        btnBdEditar.setText("Editar");
        btnBdEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBdEditarActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconsVisualizar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("*Buscar por competência");

        try {
            txtPesquisar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBdExluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBdEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(180, 180, 180)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBdExluir)
                    .addComponent(btnBdEditar)
                    .addComponent(btnPesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        setBounds(300, 150, 858, 634);
    }// </editor-fold>//GEN-END:initComponents

    private void tbBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBancoMouseClicked
       // setarCampos();
    }//GEN-LAST:event_tbBancoMouseClicked

    private void tbBancoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbBancoFocusGained
     
    }//GEN-LAST:event_tbBancoFocusGained

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         selectAll();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnBdExluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBdExluirActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, 
                        "Tem certeza que deseja excluir esse registro?",
                        "Atenção",
                        JOptionPane.YES_NO_OPTION);
        
        
        if(confirma == JOptionPane.YES_OPTION){
            String sql = "DELETE FROM tbGuias WHERE GUI_ID = ?";
            try{
                pst = conn.prepareStatement(sql);
                pst.setString(1,  tbBanco.getModel().getValueAt(tbBanco.getSelectedRow(), 0).toString());
                int apagado = pst.executeUpdate();
                
                if(apagado > 0){
                    JOptionPane.showMessageDialog(null, "Registro exluído.");
                    selectAll();
                   // tbBanco.setModel(DbUtils.resultSetToTableModel(selectAll()));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnBdExluirActionPerformed

    public void setarC(){
        int setar =  tbBanco.getSelectedRow();
        Double v1, v2, v3;
        v1 = Double.parseDouble(tbBanco.getModel().getValueAt(setar, 6).toString());
        v2 = Double.parseDouble(tbBanco.getModel().getValueAt(setar, 5).toString());
        v3 = Double.parseDouble(tbBanco.getModel().getValueAt(setar, 4).toString());
       
        txtId.setText(tbBanco.getModel().getValueAt(setar, 0).toString());
        txtNumero.setText(tbBanco.getModel().getValueAt(setar, 1).toString());
        cbSecretaria.setSelectedItem(tbBanco.getModel().getValueAt(setar, 2).toString());
    
        txtBaseCalculo.setText(tbBanco.getModel().getValueAt(setar, 3).toString());
        //txtVencimento.setText(tbGuias.getModel().getValueAt(setar, 4).toString());
        txtValServidor.setText(tbBanco.getModel().getValueAt(setar, 4).toString());
        txtValPatronal.setText(tbBanco.getModel().getValueAt(setar, 5).toString());
        txtValSuplementar.setText(tbBanco.getModel().getValueAt(setar, 6).toString());
        txtObservacao.setText(tbBanco.getModel().getValueAt(setar, 7).toString());
        
        
        SimpleDateFormat sdf = new  SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(Date.valueOf(tbBanco.getModel().getValueAt(setar, 8).toString()));
        txtData.setText(data.toString());
        v1 = v1 + v2;
        v3 = v3 + v1;
        
        txtTotalPatronal.setText(v1.toString());
        txtTotalGeral.setText(v3.toString());
        //nao permitir usuario cadastrar novamente o mesmo item
        btnSalvar.setEnabled(false);
        
    }
    private void btnBdEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBdEditarActionPerformed
        NovaGuia novaGuia = new NovaGuia();
        Principal.desktop.add(novaGuia);
        novaGuia.setVisible(true);
       
        setarC();
    }//GEN-LAST:event_btnBdEditarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBdEditar;
    private javax.swing.JButton btnBdExluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbBanco;
    public static javax.swing.JFormattedTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
